//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrinkShot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrinkShot()
        {
            this.IngrediantRecipes = new HashSet<IngrediantRecipe>();
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public string Name { get; set; }
        public string SubmittedBy { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> RatingTotal { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngrediantRecipe> IngrediantRecipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
