using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrinkShot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrinkShot()
        {
            this.IngrediantRecipes = new HashSet<IngrediantRecipe>();
            this.UserRatings = new HashSet<UserRating>();
        }
        [Required]
        [StringLength(100, ErrorMessage = "Name can only be 100 characters long")]
        public string Name { get; set; }
        
        public string SubmittedBy { get; set; }

        [Required]
        [StringLength(1000, ErrorMessage = "Instructions can only be 1000 characters long")]
        public string Instructions { get; set; }
        public Nullable<int> RatingTotal { get; set; }
        public Nullable<int> ViewCount { get; set; }
        
        public byte[] Image { get; set; }
        [Display(Name="Estimated Cost/Shot (1.25oz Liqour)")]
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        
        public List<Ingrediant> Ingredients { get; set; }
        public List<IngrediantRecipe> Recipe { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngrediantRecipe> IngrediantRecipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
