//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientRecipe
    {
        public int Id { get; set; }
        public string DSName { get; set; }
        public string IngredientName { get; set; }
        public decimal Ounces { get; set; }
        public Nullable<bool> Show { get; set; }
    
        public virtual DrinkShot DrinkShot { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
