//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DrinkShots = new HashSet<DrinkShot>();
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public string User1 { get; set; }
        public string Email { get; set; }
        public byte[] Image { get; set; }
        public string Bio { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string State { get; set; }
        public Nullable<int> Birthday { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrinkShot> DrinkShots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
